# Generated by Django 5.0.8 on 2024-09-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="listings",
            new_name="listing",
        ),
    ]
