# Generated by Django 5.0.8 on 2024-08-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
