# Generated by Django 5.0.8 on 2024-08-31 12:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("sold", "Sold"),
                    ("archived", "Archived"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
