# Generated by Django 5.0.8 on 2024-09-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_listing_created_at_listing_status"),
        ("listings", "0004_alter_favorite_listing_alter_favorite_user"),
    ]

    operations = []
