# Generated by Django 5.0.6 on 2024-06-26 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="owner",
        ),
        migrations.AlterField(
            model_name="favorite",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="listings.listing"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="listings.listing"
            ),
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="listing",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="buyer",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="seller",
        ),
        migrations.RemoveField(
            model_name="address",
            name="user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.AlterField(
            model_name="settings",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="settings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_settings",
                to="users.settings",
            ),
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("address", models.ManyToManyField(to="users.address")),
                ("user", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="Listing",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
