# Generated by Django 5.0.7 on 2024-08-16 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="user",
        ),
        migrations.AlterField(
            model_name="user",
            name="settings",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.settings",
            ),
        ),
    ]
