# Generated by Django 5.0.7 on 2024-08-16 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_settings_user_alter_user_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="settings",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.settings",
            ),
        ),
    ]
