# Generated by Django 5.0.6 on 2024-07-11 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_settings_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="settings",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_settings",
                to="users.settings",
            ),
        ),
    ]
