# Generated by Django 5.0.6 on 2024-07-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_settings_user_alter_user_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_perms",
            field=models.BooleanField(default=False),
        ),
    ]
