# Generated by Django 5.0.6 on 2024-07-11 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_has_perms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="has_perms",
        ),
    ]
